# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import runtime_pb2 as runtime__pb2


class RuntimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/SayHello',
                request_serializer=runtime__pb2.SayHelloRequest.SerializeToString,
                response_deserializer=runtime__pb2.SayHelloResponse.FromString,
                )
        self.InvokeService = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/InvokeService',
                request_serializer=runtime__pb2.InvokeServiceRequest.SerializeToString,
                response_deserializer=runtime__pb2.InvokeResponse.FromString,
                )
        self.GetConfiguration = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/GetConfiguration',
                request_serializer=runtime__pb2.GetConfigurationRequest.SerializeToString,
                response_deserializer=runtime__pb2.GetConfigurationResponse.FromString,
                )
        self.SaveConfiguration = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/SaveConfiguration',
                request_serializer=runtime__pb2.SaveConfigurationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DeleteConfiguration = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/DeleteConfiguration',
                request_serializer=runtime__pb2.DeleteConfigurationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SubscribeConfiguration = channel.stream_stream(
                '/spec.proto.runtime.v1.Runtime/SubscribeConfiguration',
                request_serializer=runtime__pb2.SubscribeConfigurationRequest.SerializeToString,
                response_deserializer=runtime__pb2.SubscribeConfigurationResponse.FromString,
                )
        self.TryLock = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/TryLock',
                request_serializer=runtime__pb2.TryLockRequest.SerializeToString,
                response_deserializer=runtime__pb2.TryLockResponse.FromString,
                )
        self.Unlock = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/Unlock',
                request_serializer=runtime__pb2.UnlockRequest.SerializeToString,
                response_deserializer=runtime__pb2.UnlockResponse.FromString,
                )
        self.GetNextId = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/GetNextId',
                request_serializer=runtime__pb2.GetNextIdRequest.SerializeToString,
                response_deserializer=runtime__pb2.GetNextIdResponse.FromString,
                )
        self.GetState = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/GetState',
                request_serializer=runtime__pb2.GetStateRequest.SerializeToString,
                response_deserializer=runtime__pb2.GetStateResponse.FromString,
                )
        self.GetBulkState = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/GetBulkState',
                request_serializer=runtime__pb2.GetBulkStateRequest.SerializeToString,
                response_deserializer=runtime__pb2.GetBulkStateResponse.FromString,
                )
        self.SaveState = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/SaveState',
                request_serializer=runtime__pb2.SaveStateRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DeleteState = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/DeleteState',
                request_serializer=runtime__pb2.DeleteStateRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DeleteBulkState = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/DeleteBulkState',
                request_serializer=runtime__pb2.DeleteBulkStateRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ExecuteStateTransaction = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/ExecuteStateTransaction',
                request_serializer=runtime__pb2.ExecuteStateTransactionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.PublishEvent = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/PublishEvent',
                request_serializer=runtime__pb2.PublishEventRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetFile = channel.unary_stream(
                '/spec.proto.runtime.v1.Runtime/GetFile',
                request_serializer=runtime__pb2.GetFileRequest.SerializeToString,
                response_deserializer=runtime__pb2.GetFileResponse.FromString,
                )
        self.PutFile = channel.stream_unary(
                '/spec.proto.runtime.v1.Runtime/PutFile',
                request_serializer=runtime__pb2.PutFileRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ListFile = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/ListFile',
                request_serializer=runtime__pb2.ListFileRequest.SerializeToString,
                response_deserializer=runtime__pb2.ListFileResp.FromString,
                )
        self.DelFile = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/DelFile',
                request_serializer=runtime__pb2.DelFileRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetFileMeta = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/GetFileMeta',
                request_serializer=runtime__pb2.GetFileMetaRequest.SerializeToString,
                response_deserializer=runtime__pb2.GetFileMetaResponse.FromString,
                )
        self.InvokeBinding = channel.unary_unary(
                '/spec.proto.runtime.v1.Runtime/InvokeBinding',
                request_serializer=runtime__pb2.InvokeBindingRequest.SerializeToString,
                response_deserializer=runtime__pb2.InvokeBindingResponse.FromString,
                )


class RuntimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """SayHello used for test
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeService(self, request, context):
        """InvokeService do rpc calls
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfiguration(self, request, context):
        """GetConfiguration gets configuration from configuration store.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveConfiguration(self, request, context):
        """SaveConfiguration saves configuration into configuration store.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConfiguration(self, request, context):
        """DeleteConfiguration deletes configuration from configuration store.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeConfiguration(self, request_iterator, context):
        """SubscribeConfiguration gets configuration from configuration store and subscribe the updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TryLock(self, request, context):
        """Distributed Lock API
        A non-blocking method trying to get a lock with ttl.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextId(self, request, context):
        """Sequencer API
        Get next unique id with some auto-increment guarantee
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Below are the APIs compatible with Dapr.
        We try to keep them same as Dapr's because we want to work with Dapr to build an API spec for cloud native runtime
        ,like CloudEvent for event data.

        Gets the state for a specific key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBulkState(self, request, context):
        """Gets a bulk of state items for a list of keys
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveState(self, request, context):
        """Saves an array of state objects
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteState(self, request, context):
        """Deletes the state for a specific key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBulkState(self, request, context):
        """Deletes a bulk of state items for a list of keys
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteStateTransaction(self, request, context):
        """Executes transactions for a specified store
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishEvent(self, request, context):
        """Publishes events to the specific topic
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """Get file with stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutFile(self, request_iterator, context):
        """Put file with stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFile(self, request, context):
        """List all files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DelFile(self, request, context):
        """Delete specific file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileMeta(self, request, context):
        """Get file meta data, if file not exist,return code.NotFound error
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeBinding(self, request, context):
        """Invokes binding data to specific output bindings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=runtime__pb2.SayHelloRequest.FromString,
                    response_serializer=runtime__pb2.SayHelloResponse.SerializeToString,
            ),
            'InvokeService': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeService,
                    request_deserializer=runtime__pb2.InvokeServiceRequest.FromString,
                    response_serializer=runtime__pb2.InvokeResponse.SerializeToString,
            ),
            'GetConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfiguration,
                    request_deserializer=runtime__pb2.GetConfigurationRequest.FromString,
                    response_serializer=runtime__pb2.GetConfigurationResponse.SerializeToString,
            ),
            'SaveConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveConfiguration,
                    request_deserializer=runtime__pb2.SaveConfigurationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConfiguration,
                    request_deserializer=runtime__pb2.DeleteConfigurationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SubscribeConfiguration': grpc.stream_stream_rpc_method_handler(
                    servicer.SubscribeConfiguration,
                    request_deserializer=runtime__pb2.SubscribeConfigurationRequest.FromString,
                    response_serializer=runtime__pb2.SubscribeConfigurationResponse.SerializeToString,
            ),
            'TryLock': grpc.unary_unary_rpc_method_handler(
                    servicer.TryLock,
                    request_deserializer=runtime__pb2.TryLockRequest.FromString,
                    response_serializer=runtime__pb2.TryLockResponse.SerializeToString,
            ),
            'Unlock': grpc.unary_unary_rpc_method_handler(
                    servicer.Unlock,
                    request_deserializer=runtime__pb2.UnlockRequest.FromString,
                    response_serializer=runtime__pb2.UnlockResponse.SerializeToString,
            ),
            'GetNextId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextId,
                    request_deserializer=runtime__pb2.GetNextIdRequest.FromString,
                    response_serializer=runtime__pb2.GetNextIdResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=runtime__pb2.GetStateRequest.FromString,
                    response_serializer=runtime__pb2.GetStateResponse.SerializeToString,
            ),
            'GetBulkState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBulkState,
                    request_deserializer=runtime__pb2.GetBulkStateRequest.FromString,
                    response_serializer=runtime__pb2.GetBulkStateResponse.SerializeToString,
            ),
            'SaveState': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveState,
                    request_deserializer=runtime__pb2.SaveStateRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteState': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteState,
                    request_deserializer=runtime__pb2.DeleteStateRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteBulkState': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBulkState,
                    request_deserializer=runtime__pb2.DeleteBulkStateRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ExecuteStateTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteStateTransaction,
                    request_deserializer=runtime__pb2.ExecuteStateTransactionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'PublishEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishEvent,
                    request_deserializer=runtime__pb2.PublishEventRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetFile': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=runtime__pb2.GetFileRequest.FromString,
                    response_serializer=runtime__pb2.GetFileResponse.SerializeToString,
            ),
            'PutFile': grpc.stream_unary_rpc_method_handler(
                    servicer.PutFile,
                    request_deserializer=runtime__pb2.PutFileRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFile,
                    request_deserializer=runtime__pb2.ListFileRequest.FromString,
                    response_serializer=runtime__pb2.ListFileResp.SerializeToString,
            ),
            'DelFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DelFile,
                    request_deserializer=runtime__pb2.DelFileRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetFileMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileMeta,
                    request_deserializer=runtime__pb2.GetFileMetaRequest.FromString,
                    response_serializer=runtime__pb2.GetFileMetaResponse.SerializeToString,
            ),
            'InvokeBinding': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeBinding,
                    request_deserializer=runtime__pb2.InvokeBindingRequest.FromString,
                    response_serializer=runtime__pb2.InvokeBindingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spec.proto.runtime.v1.Runtime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Runtime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/SayHello',
            runtime__pb2.SayHelloRequest.SerializeToString,
            runtime__pb2.SayHelloResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InvokeService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/InvokeService',
            runtime__pb2.InvokeServiceRequest.SerializeToString,
            runtime__pb2.InvokeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/GetConfiguration',
            runtime__pb2.GetConfigurationRequest.SerializeToString,
            runtime__pb2.GetConfigurationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/SaveConfiguration',
            runtime__pb2.SaveConfigurationRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/DeleteConfiguration',
            runtime__pb2.DeleteConfigurationRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubscribeConfiguration(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/spec.proto.runtime.v1.Runtime/SubscribeConfiguration',
            runtime__pb2.SubscribeConfigurationRequest.SerializeToString,
            runtime__pb2.SubscribeConfigurationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TryLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/TryLock',
            runtime__pb2.TryLockRequest.SerializeToString,
            runtime__pb2.TryLockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Unlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/Unlock',
            runtime__pb2.UnlockRequest.SerializeToString,
            runtime__pb2.UnlockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNextId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/GetNextId',
            runtime__pb2.GetNextIdRequest.SerializeToString,
            runtime__pb2.GetNextIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/GetState',
            runtime__pb2.GetStateRequest.SerializeToString,
            runtime__pb2.GetStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBulkState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/GetBulkState',
            runtime__pb2.GetBulkStateRequest.SerializeToString,
            runtime__pb2.GetBulkStateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/SaveState',
            runtime__pb2.SaveStateRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/DeleteState',
            runtime__pb2.DeleteStateRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteBulkState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/DeleteBulkState',
            runtime__pb2.DeleteBulkStateRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteStateTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/ExecuteStateTransaction',
            runtime__pb2.ExecuteStateTransactionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PublishEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/PublishEvent',
            runtime__pb2.PublishEventRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/spec.proto.runtime.v1.Runtime/GetFile',
            runtime__pb2.GetFileRequest.SerializeToString,
            runtime__pb2.GetFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/spec.proto.runtime.v1.Runtime/PutFile',
            runtime__pb2.PutFileRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/ListFile',
            runtime__pb2.ListFileRequest.SerializeToString,
            runtime__pb2.ListFileResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DelFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/DelFile',
            runtime__pb2.DelFileRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFileMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/GetFileMeta',
            runtime__pb2.GetFileMetaRequest.SerializeToString,
            runtime__pb2.GetFileMetaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InvokeBinding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spec.proto.runtime.v1.Runtime/InvokeBinding',
            runtime__pb2.InvokeBindingRequest.SerializeToString,
            runtime__pb2.InvokeBindingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
